name: Build on Linux
on:
  push:
    branches:
      - rust

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      ARCH: "${{ endsWith(matrix.os, 'arm') && 'aarch64' || 'x86_64' }}"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev desktop-file-utils
          rustup update
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Install libcontemporary utils
        run: |
          git clone https://github.com/vicr123/contemporary-rs
          cargo install --path ./contemporary-rs/deploy_tool/cargo_cntp_bundle
          cargo install --path ./contemporary-rs/deploy_tool/cargo_cntp_deploy
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: cargo cntp-bundle
        working-directory: thebeat
      - name: Deploy
        run: cargo cntp-deploy --output-file "$HOME/theBeat-$ARCH.AppImage"
        working-directory: thebeat
      - uses: actions/upload-artifact@v4
        with:
          name: theBeat-linux-${{ env.ARCH }}
          path: "~/theBeat-${{ env.ARCH }}.AppImage"
