name: "macOS CI"
on:
  push:
    branches:
      - '**'
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.7.0'
          target: 'desktop'
          arch: 'clang_64'
          cache: true
          modules: 'qt3d qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebengine qtwebsockets qtwebview qt5compat qtquick3d qtquicktimeline qtshadertools'
      - name: Install QCoro
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: danvratil/qcoro
          commitish: v0.10.0
      - name: Install libcontemporary
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: theCheeseboard/libcontemporary
          commitish: features/qml
      - name: Install contemporary-qml
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: theCheeseboard/contemporary-qml
          commitish: main
      - name: Install utfcpp
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: nemtrif/utfcpp
          commitish: v4.0.5
      - name: Install taglib
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: taglib/taglib
          commitish: v2.0.2
          extra-cmake-args: -DBUILD_SHARED_LIBS=ON
      - name: Install libmusicbrainz
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: metabrainz/libmusicbrainz
          commitish: release-5.1.0
          extra-cmake-args: -DBUILD_SHARED_LIBS=ON
      - name: Install thebeat
        id: thebeat
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: .
          commitish: .
      - name: Deploy thebeat
        uses: theCheeseboard/actions/deploy-project@actions
        with:
          sourceDirectory: ${{ steps.thebeat.outputs.source-directory }}
          buildDirectory: ${{ steps.thebeat.outputs.build-directory }}
