name: "Windows CI"
on:
  push:
    branches:
      - '**'
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '>=3.1.18'
          version: '6.8.1'
          arch: 'win64_msvc2022_64'
          target: 'desktop'
          cache: true
          modules: 'qt3d qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview qt5compat qtquick3d qtquicktimeline qtshadertools'
      - name: Install QCoro
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: danvratil/qcoro
          commitish: v0.10.0
      - name: Install utfcpp
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: nemtrif/utfcpp
          commitish: v4.0.5
      - name: Install taglib
        uses: theCheeseboard/actions/build-cmake-project@actions
        id: taglib
        with:
          project: taglib/taglib
          commitish: v2.0.2
          extra-cmake-args: -DBUILD_SHARED_LIBS=ON
      - name: Install libcontemporary
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: theCheeseboard/libcontemporary
          commitish: features/qml
      - name: Install contemporary-qml
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: theCheeseboard/contemporary-qml
          commitish: main
      - name: Install thebeat
        id: thebeat
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: .
          commitish: .
          extra-cmake-args: |
              -DTAGLIB_ROOT=${{ steps.taglib.outputs.install-directory }} "-DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"
      - name: Deploy thebeat
        env:
          SOURCE_DIRECTORY: ${{ steps.thebeat.outputs.source-directory }}
          BUILD_DIRECTORY: ${{ steps.thebeat.outputs.build-directory }}
          INSTALL_DIRECTORY: ${{ steps.thebeat.outputs.install-directory }}
        run: |
          New-Item -ItemType Directory -Force -Path output
          $executable = Move-Item -Path "$env:BUILD_DIRECTORY/thebeat*.exe" -Destination output -Force -PassThru
          windeployqt output --qmldir="$env:SOURCE_DIRECTORY" -printsupport
          copy $env:INSTALL_DIRECTORY/bin/*.dll output
      - name: Upload thebeat artifact
        uses: actions/upload-artifact@v4
        with:
          name: thebeat-win
          path: output
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-mixed-release
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows
      VCPKG_FORCE_SYSTEM_BINARIES: 1
