name: Build on Windows
on:
  push:
    branches:
      - rust

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, windows-11-arm ]
    runs-on: ${{ matrix.os }}
    env:
      ARCH: "${{ endsWith(matrix.os, 'arm') && 'aarch64' || 'x86_64' }}"
    steps:
      - name: Generate build UUID
        id: build_uuid
        run: |
          $BUILD_UUID = [guid]::NewGuid().ToString()
          echo "BUILD_UUID=$BUILD_UUID" >> $env:GITHUB_OUTPUT
          echo "BIN_CHICKEN_UUID=$BUILD_UUID" >> $env:GITHUB_ENV
          echo "The UUID for this build is $BUILD_UUID"
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Install Rust
        if: matrix.os == 'windows-11-arm'
        run: |
          Invoke-WebRequest https://win.rustup.rs/aarch64 -OutFile rustup.exe
          .\rustup.exe default stable
          $CargoLocation = .\rustup.exe which cargo
          Add-Content -Path "$env:GITHUB_PATH" -Value ([System.IO.Path]::GetDirectoryName($CargoLocation))
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Install libcontemporary utils
        run: |
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-bundle
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-deploy
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: cargo cntp-bundle
        working-directory: thebeat
      - name: Deploy
        run: cargo cntp-deploy --output-file "$env:GITHUB_WORKSPACE/theBeat-$env:ARCH.exe"
        working-directory: thebeat
      - uses: actions/upload-artifact@v4
        with:
          name: theBeat-windows-${{ env.ARCH }}
          path: "theBeat-${{ env.ARCH }}.exe"
      - name: Print build UUID
        env:
          BUILD_UUID: ${{ steps.build_uuid.outputs.BUILD_UUID }}
        run: echo "$env:BUILD_UUID" > build_uuid.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build_uuid-${{ env.ARCH }}
          path: build_uuid.txt
  bin-chicken:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    env:
      ARCH: "${{ endsWith(matrix.os, 'arm') && 'aarch64' || 'x86_64' }}"
    steps:
      - name: Install minisign
        run: |
          sudo apt-get update
          sudo apt-get install -y minisign
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: theBeat-windows-${{ env.ARCH }}
      - name: Download build UUID
        uses: actions/download-artifact@v4
        with:
          name: build_uuid-${{ env.ARCH }}
      - name: Sign artifact
        env:
          MINISIGN_PRIV_KEY: ${{ secrets.MINISIGN_KEY }}
        run: |
          printf '%s' "$MINISIGN_PRIV_KEY" > minisign.key
          minisign -S -s minisign.key -m theBeat-${{ env.ARCH }}.exe
      - name: Upload to bin-chicken
        env:
          BIN_CHICKEN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BIN_CHICKEN_CHANNEL: blueprint
          BIN_CHICKEN_TARGET: ${{ env.ARCH }}-pc-windows-msvc
          BIN_CHICKEN_REPOSITORY: thebeat
          UPLOAD_FILE: theBeat-${{ env.ARCH }}.exe
        run: |
          curl -v --fail-with-body -T $UPLOAD_FILE \
            -H "Authorization: Bearer $BIN_CHICKEN_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            -H "X-Bin-Chicken-Channel: $BIN_CHICKEN_CHANNEL" \
            -H "X-Bin-Chicken-Target: $BIN_CHICKEN_TARGET" \
            -H "X-Bin-Chicken-Original-Filename: $UPLOAD_FILE" \
            -H "X-Bin-Chicken-UUID: $(cat build_uuid.txt)" \
            -H "X-Bin-Chicken-Signature: $(cat $UPLOAD_FILE.minisig | base64 -w 0)" \
            https://binchicken.vicr123.com/api/repositories/$BIN_CHICKEN_REPOSITORY